C$PROG IFIND
      FUNCTION IFIND(IBY,ITST,IA,IB)
C
      BYTE IBY(1)
C
      INTEGER*4   X3B,X21
      DATA        X3B,X21/'3B'X,'21'X/
C
C     FUNCTION TO RETURN THE LOCATION OF TEST BYTE "ITST" IN IBY
C
      IFIND=0
C
      DO 10 I=IA,IB
      JTEMP=IBY(I)
      IF(JTEMP.EQ.X3B) RETURN
      IF(JTEMP.EQ.X21) RETURN
      IF(JTEMP.EQ.ITST)  GO TO 20
   10 CONTINUE
      RETURN
   20 IFIND=I
      RETURN
      END
