C$PROG JOCO
C
C     ************************************************************
C     BY WT MILNER AT HHIRF - LAST MODIFIED 04/30/90
C     ************************************************************
C
      FUNCTION JOCO(IWD,IERR)
C   
      COMMON/LLL/  MSSG(28),NAMPROG(2),LOGUT,LOGUP,LISFLG,MSGF
C
      CHARACTER*112 CMSSG
C
      EQUIVALENCE (CMSSG,MSSG)
C
      INTEGER*4 IWD(2),NSH(7)
C
      DATA (NSH(I),I=1,7)/0,3,6,9,12,15,18/
C
      DATA IBLN,IHEX,IOCT/'20'X,'48'X,'42'X/
C
      INTEGER*4   X30,X37
      DATA        X30,X37/'30'X,'37'X/
C
      SAVE
C
C     DECODES A STRING OF RIGHT-JUSTIFIED CHARACTERS AS DEC, HEX
C
      IERR=0
      CALL ILBYTE(JT,IWD,7)
      IF(JT.EQ.IHEX) GO TO 100
      IF(JT.EQ.IOCT) GO TO 200
C
C     IT IS A DECIMAL INTEGER - CALL MILV
C
      CALL MILV(IWD,IV,XV,KIND,IERR)
      IF(IERR.NE.0) GO TO 310
      IF(KIND.NE.1) GO TO 300
      JOCO=IV
      RETURN
C
C     IT IS A HEX INTEGER - CALL HEXVAL
C
  100 CALL HEXVAL(IWD,IV,IERR)
      IF(IERR.NE.0) GO TO 310
      JOCO=IV
      RETURN
C
C     IT IS AN OCTAL STRING - DO BYTE-BY-BYTE
C
  200 N=7
      ISUM=0
      DO 220 I=1,7
      CALL ILBYTE(JT,IWD,N-1)
      IF(JT.EQ.IBLN) GO TO 230
      IF(JT.LT.X30.OR.JT.GT.X37) GO TO 300
      JT=IAND(JT,7)
      ISUM=ISUM+ISHFT(JT,NSH(I))
      N=N-1
  220 CONTINUE
  230 JOCO=ISUM
      RETURN
C
  300 WRITE(CMSSG,305)IWD
  305 FORMAT('SYNTAX ERROR IN INTEGER OR OCTAL VALUE = ',2A4)
      CALL ERRLOG(LOGUT,LOGUP)
      IERR=1
  310 JOCO=0
      RETURN
      END
