#!/bin/csh -f
echo " "
echo "Using   /tera/mcsq/Dlinux/Dvme/testvme"
echo " "
echo "*********************** WARNING ************************"
echo "*  Normal Acquisition Codes in the VME processor are   *"
echo "*  being replaced with test programs.  These test      *"
echo "*  programs generate an event stream for testing the   *"
echo "*  VME/workstation connection.                         *"
echo "*                                                      *"
echo "* NOTE: When finished testing, you should execute the  *"
echo "*       the command - loadacq                          *"
echo "*********************** WARNING ************************"
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/kill_acq
set err = $status
if ($err != 0) then
  echo "${0}: Cannot Kill Acquisition System - Error Status = $err"
  exit
endif
echo "Delete the acquisition tasks in the VME processor"
/tera/mcsq/Dlinux/Dvme/kt data_proc >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt testvme >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt VMEtest >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt VMEacq >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt DSSDacq >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt vmemon >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt vmexx >& /dev/null
echo " "
echo "Now load the VME/DECstation test programs."
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/data_proc
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'data_proc' - Error Status = $err"
  exit
endif
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/testvme 1024
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'testvme' - Error Status = $err"
  exit
endif
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/VMEtest
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'VMEtest' - Error Status = $err"
  exit
endif
echo " "
echo "VME/DECstation test codes are now loaded."
