C$PROG ESP
      SUBROUTINE ESP
      IMPLICIT REAL*8(A-H,O-Z)
      character*4 ABSORB
c     INTEGER ABSORB
      COMMON/AAA/ V(4), NZ(30), CONST(50), ZZ(25)
      DIMENSION Q(10), THETA(10), CMTOLB(10), E3(10), THCM3(10),
     1 DEXIT(10), XI2PP(10), A(10), DTFP(10), DK(10),
     2ANOK(10), RDIST(10), IJ(10), EL(10),JRAK(6),
     3 TBACK(2)
      DIMENSION IATM(4)
      DIMENSION FXFUK(2)
      EQUIVALENCE (NZ(9),JRAK(1)),(CONST(19),DEGRAD),
     1(CONST(26),SE), (CONST(34),XA)
C   
      EQUIVALENCE (SOLN2 ,ZZ(1)),
     &            (IFLAG ,ZZ(3)),
     &            (TWO   ,ZZ(13))
C   
C
      CHARACTER*320 CLWD
C
      INTEGER*4 IWD(20),LWD(2,40),ITYP(40)
C
      EQUIVALENCE (CLWD,LWD)
C
      DATA TRUE,FALSE/1.0,0.0/
C   
C     ******************************************************************
C     SUBROUTINE ESP TAKES THE FIRST Q-VALUE AND ANOTHER Q-VALUE
C     TO DETERMIN THE MAGNET FIELD AND THE CORRESPONDING FREQUENCY
C     AND TO DETERMINE THE LEFT AND RIGHT DIAL READINGS.
C     ******************************************************************
C   
      IMIN=1
      IMAX=80
    1 READ(5,51)JRAK
   51 FORMAT(6A4)
      READ(5,50)IWD
   50 FORMAT(20A4)
      CALL GREAD(IWD,LWD,ITYP,NF,IMIN,IMAX,NTER)
      READ(CLWD,22)DTHETA,ZOUT,EIN,FLAG,IENGY,FXFUK
      ISOLN2=FXFUK(1)+0.5
      IMASS=FXFUK(2)+0.5
      IF (DTHETA.EQ.0.0) GO TO 12
      IF(IMASS.NE.0.0)GO TO 60
   71 READ(5,50)IWD
      CALL GREAD(IWD,LWD,ITYP,NF,IMIN,IMAX,NTER)
      READ(CLWD,18)TARGT,TBACK,TBACKT,ZTB,FXFUK(1),ABSORB
      GO TO 70
   60 READ(5,50)IWD
      CALL GREAD(IWD,LWD,ITYP,NF,IMIN,IMAX,NTER)
      READ(CLWD,21)V
      GO TO 71
   70 CONTINUE
      NORDER=FXFUK(1)+0.5
      READ(5,50)IWD
      CALL GREAD(IWD,LWD,ITYP,NF,IMIN,IMAX,NTER)
      READ(CLWD,23)Q
      READ(5,50)IWD
      CALL GREAD(IWD,LWD,ITYP,NF,IMIN,IMAX,NTER)
      READ(CLWD,23)ANGI,ANGFI,DEL
      READ(5,50)IWD
      CALL GREAD(IWD,LWD,ITYP,NF,IMIN,IMAX,NTER)
      READ(CLWD,23)FXFUK(1),FXFUK(2),RHOD
      NQ=FXFUK(1)+0.5
      INQ=FXFUK(2)+0.5
      IF (NQ.GT.10.OR.INQ.GT.10.OR.INQ.LE.1.OR.INQ.GT.NQ) GO TO 11
      IFLAG=FLAG
      DTHET = DTHETA
      TARGB=2*TBACKT
      EI=EIN
      IF (ISOLN2.EQ.2) SOLN2= TRUE
      IF(IMASS.NE.0) GO TO 2
      CALL PARTFI(JRAK,24,V,IATM,NZ,QGS,IFAIL,ISOR)
      IF (IFAIL.EQ.0) GO TO 2
      WRITE(7,26)JRAK
      GO TO 1
2     XM1A=V(1)
      XM2A=V(2)
      XM3A=V(3)
      XM4A=V(4)
      CALL ENERGY (Q,EL,IENGY,QGS,NQ)
      DTHETA=DTHETA*DEGRAD/2.
      T=XM3A*XA
      TERMX=SE/ZOUT
      THDEG=ANGI
C   
C     NORDER = 1 FOR BACKING FIRST
C     NORDER = 2 FOR BACKING SECOND
C   
      ZT = NZ(2)
      ZZ(7) = ZT
      ZZ(11) = ZTB
      ZPOUT = NZ(3)
      ZPIN = NZ(1)
      IF (TARGT.EQ.0.0) GO TO 3
      IF (NORDER.EQ.1.AND.TBACKT.NE.0.0) CALL ELOSS (EIN,ZPIN,XM1A,
     XZTB,TARGB,'SOLI')
c    XZTB,TARGB,4HSOLI)
      CALL ELOSS(EIN,ZPIN,XM1A,ZT,TARGT,ABSORB)
3     ETARG = EIN
4     THETA(1)=THDEG*DEGRAD
      DO 9 J=1,NQ
      CALL RELKIN  (XM1A,XM2A,XM3A,XM4A,EIN,THETA,THCM3(J),CMTOLB(J),E3(
     1J),Q(J),IJ(J))
      IF (IJ(J).EQ.0) GO TO 1
      IF (TARGT.EQ.0.0) GO TO 5
      CALL ELOSS(E3(J),ZPOUT,XM3A,ZT,TARGT,ABSORB)
      IF (NORDER.EQ.2.AND.TBACKT.NE.0.0) CALL ELOSS (E3(J),ZPOUT,XM3A,
     XZTB,TARGB,'SOLI')
c    XZTB,TARGB,4HSOLI)
5     IF (J.NE.1) GO TO 6
      BD=TERMX*(DSQRT(E3(1)**2+2.*T*E3(1)))/RHOD
      FD=4.2578*BD
6     RECOIL=XM1A+XM2A-XM3A-Q(J)/XA
      A(J)=TERMX*DSQRT(E3(J)**2+2.*T*E3(J))/BD
      IF (A(J)-30.) 7,8,8
 7    WRITE(7,27)THDEG,J
      GO TO 9
8     CALL OPTIC (A(J),E3(J),XM1A,XM3A,EIN,THETA,DTHETA,RECOIL,DTFP(J),D
     1EXIT(J),XI2PP(J),DK(J),ANOK(J))
9     CONTINUE
      CALL WHERE (Q,INQ,DEXIT,DTFP,XI2PP,TL,TR,RDIST,IJ,NQ)
C   
      WRITE(7,14)JRAK,QGS,EI,ETARG,XM1A,TARGT,XM2A,TBACK(1),TBACK(2),
     1XM3A,TBACKT,XM4A,NORDER,ZOUT
      WRITE(7,17)BD,FD
      WRITE(7,16)THDEG,DTHET
      IF(SOLN2.EQ.1.0) WRITE(7,20)
      IF(TWO.EQ.1.0) WRITE(7,19)
      WRITE(7,28)
      DO 10 J=1,NQ
      WRITE(7,29)Q(J),THCM3(J),CMTOLB(J),E3(J),A(J),ANOK(J),DK(J),RDIST(
     1J),EL(J)
      IF (J.EQ.1.OR.J.EQ.INQ) WRITE(7,13)
10    CONTINUE
      WRITE(7,15)TL,TR
C   
      THDEG=THDEG+DEL
      IF (THDEG-ANGFI) 4,4,1
 11   WRITE(7,30)
12    RETURN
C   
C   
C     ------------------------------------------------------------------
C
13    FORMAT (1H+,94X,'FOCAL PLANE SET')
14    FORMAT (1H1,50X,'OUTPUT FOR SUBROUTINE ESP      ',///,' ',58X,
     1'REACTION',/,' ',53X,6A4,/,51X,' QGS =',F10.5,'  MEV',///,
     2' KINEMATIC VARIABLES * * * * EBOMB(LAB) =',F10.5,'  MEV',10X,
     3'ENERGY LOSS INFO * * * * ETARGET =',F10.5,'  MEV/',37X,' M1 =',
     4F10.5,'  AMU',26X,'TARGET THICKNESS =',F10.5,'MG/SQ-CM',/,37X,
     5' M2 =',F10.5,'  AMU',28X,'TARGET BACKING =',2A4,/,37X,' M3 =',
     6F10.5,'  AMU',24X,' BACKING THICKNESS =',F10.5,'MG/SQ-CM',/,37X,
     7' M4 =',F10.5,'  AMU',29X,'BACKING ORDER =',I4,/,36X,'ZOUT =',
     8F5.0,/)
15    FORMAT (//,42X,21H  LEFT DIAL READING =,F10.5,/,42X,21H RIGHT DIAL
     1 READING =,F10.5)
16    FORMAT (//,42X,21H REACTION LAB ANGLE =,F10.5,5H  DEG,/,53X,10HAPE
     1RTURE =,F10.5,5H  DEG,//)
17    FORMAT (/,48X,15H MAGNET FIELD =,F10.5,11H  KILOGAUSS,/,51X,12H FR
     1EQUENCY =,F10.5,11H  MEGAHERTZ,//)
   18 FORMAT(E8.0,2A4,3E8.0,A4)
19    FORMAT (54H TWO SOLN TO RELKIN***PUNCH A 2 IN COL 73 OF JRAK CARD/
     1)
20    FORMAT (38H CALCULATION FOR SECOND SOLN TO RELKIN,//)
21    FORMAT (8F10.6)
   22 FORMAT(4E8.0,A4,4X,2E8.0)
   23 FORMAT(10E8.0)
26    FORMAT (14H1FINDER FAILED,10X,6A4)
27    FORMAT (1H ,17H LESS THAN 30. CM,F9.5,2I5)
28    FORMAT (1H ,8H Q VALUE,2X,10H THETA3 CM,3X,7H CMTOLB,3X,7H E3 LAB,
     13X,4H RHO,6X,9H .5DE/EDT,10H KIN SHIFT,3X,6H RDIST,3X,7H ELEVEL,/)
29    FORMAT (1H ,2F10.4,F10.5,2F10.4,F10.5,2X,3F10.4)
30    FORMAT (44H CHECK ESP INPUT VARIABLES NQ OR INQ        )
      END
