fatrumplib:\
fatrumplib.a(buflod.o)\
fatrumplib.a(calbra.o)\
fatrumplib.a(chanfi.o)\
fatrumplib.a(consts.o)\
fatrumplib.a(crow.o)\
fatrumplib.a(det.o)\
fatrumplib.a(distan.o)\
fatrumplib.a(eloss.o)\
fatrumplib.a(energy.o)\
fatrumplib.a(esp.o)\
fatrumplib.a(calbra.o)\
fatrumplib.a(chanfi.o)\
fatrumplib.a(consts.o)\
fatrumplib.a(crow.o)\
fatrumplib.a(distan.o)\
fatrumplib.a(eloss.o)\
fatrumplib.a(energy.o)\
fatrumplib.a(esp.o)\
fatrumplib.a(magnet.o)\
fatrumplib.a(nufreq.o)\
fatrumplib.a(optic.o)\
fatrumplib.a(qend.o)\
fatrumplib.a(relkin.o)\
fatrumplib.a(rho.o)\
fatrumplib.a(tune.o)\
fatrumplib.a(where.o)\
fatrumplib.a(redstop.o)\
fatrumplib.a(buflod.o)\
fatrumplib.a(partfi.o)\
fatrumplib.a(det.o)\
fatrumplib.a(fit3.o)\
fatrumplib.a(fit3.o)\
fatrumplib.a(magnet.o)\
fatrumplib.a(nufreq.o)\
fatrumplib.a(optic.o)\
fatrumplib.a(partfi.o)\
fatrumplib.a(qend.o)\
fatrumplib.a(redstop.o)\
fatrumplib.a(relkin.o)\
fatrumplib.a(rho.o)\
fatrumplib.a(tune.o)\
fatrumplib.a(where.o)
	ranlib fatrumplib.a
	@echo fatrumplib is up-to-date
#
FFLAGS= $(OPT) $(FARGS)
#
.f.o:
	$(F77) -c $(FFLAGS) $<
#
#	ar rv fatrumplib.a $*.o

