C$PROG TUNE
      SUBROUTINE TUNE (A,E,TH,DTH,ZO,B,TB,TMXB,   RD,DRD,TOL,TL,TR,Q,N,K
     1)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION A(4), Q(2), RD(2)
C   
C   
      NIT=50
      BO=B
      STEP=0.2
      DIR=1.0
      IF (RD(1).GT.DRD) DIR=-DIR
      RS=RD(1)
C   
C     RD(1) IS PLACE WHERE PARTICLE IS NOW FALLING
C     DRD IS THE DESIRED RD
C   
      DO 1 NI=1,NIT
      B=B*(1.0+DIR*STEP)
      CALL CROW (A,E,TH,DTH,ZO,B,TB,TMXB,   RD,TL,TR,Q,N,K)
      IF (ABS (RD(1)-DRD).LE.TOL) GO TO 2
C   
C     SEE IF YOU OVERSHOT, IF SO REDUCE STEP SIZE AND CHANGE DIRECTIONS
C   
      IF (RD(1).GT.DRD.AND.DIR.LT.0.0) GO TO 1
      IF (RD(1).LT.DRD.AND.DIR.GT.0.0) GO TO 1
      DIR=-DIR
      STEP=0.2*STEP
1     CONTINUE
      WRITE(7,3)
2     RETURN
C   
C   
3     FORMAT (93H MAXIMUM NUMBER OF ITTERATIONS REACHED IN SUBROUTINE TU
     1NE * * * * RESULTS MAY BE INACCURATE. )
      END
