#!/bin/csh
make -f acq_run.make install
make -f caenr.make install
make -f caenw.make install
make -f cnaf.make install
make -f docnaf.make install
make -f femsg.make install
make -f fifo.make install
make -f ipcmon.make install
make -f logger.make install
#make -f modu_setup.make install
make -f m_setup.make install
cd pacor; make install
cd ../
make -f udpmon.make install
make -f vmehardware.make install
