#!/bin/csh -f
/usr/acq/vme/run /usr/acq/vme/kill_acq
set err = $status
if ($err != 0) then
  echo "${0}: Cannot Kill Acquisition System - Error Status = $err"
  exit
endif
echo "Delete the acquisition tasks in the VME processor"
/usr/acq/vme/kt data_proc >& /dev/null
/usr/acq/vme/kt testvme >& /dev/null
/usr/acq/vme/kt VMEtest >& /dev/null
/usr/acq/vme/kt VMEacq >& /dev/null
/usr/acq/vme/kt DSSDacq >& /dev/null
/usr/acq/vme/kt vmemon >& /dev/null
echo " "
echo "Now load the acquisition tasks.  Any error messages here are BAD news."
/usr/acq/vme/run /usr/acq/vme/data_proc
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'data_proc' - Error Status = $err"
  exit
endif
/usr/acq/vme/run /usr/acq/vme/DSSDacq 1536
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'DSSDacq' - Error Status = $err"
  exit
endif
