C$PROG CKMOTY
C
C     ************************************************************
C     BY WT MILNER AT HHIRF - LAST MODIFIED 06/02/2001
C                             for CAEN support
C     ************************************************************
C
      SUBROUTINE CKMOTY(KINMOD,MOTYP)
C
      COMMON/LLL/  MSSG(28),NAMPROG(2),LOGUT,LOGUP,LISFLG,MSGF
C
      COMMON/PACO/ KODLO(4),KODHI(4)
C
      CHARACTER*112 CMSSG
C
      EQUIVALENCE (CMSSG,MSSG)
C
      CHARACTER*4  KINMOD
C
      SAVE
C
      IF(KINMOD.EQ.'$FER') GO TO 20
      IF(KINMOD.EQ.'$FAS') GO TO 40
      IF(KINMOD.EQ.'$CAM') GO TO 60
      IF(KINMOD.EQ.'$VME') GO TO 80
      RETURN
C
   20 IF(MOTYP.GE.KODLO(1).AND.MOTYP.LE.KODHI(1)) RETURN
C
      WRITE(CMSSG,25)
   25 FORMAT('ILLEGAL OR UNDEFINED FERRA MODULE TYPE')
      CALL ERRLOG(LOGUT,LOGUP)
      RETURN
C
   40 IF(MOTYP.GE.KODLO(2).AND.MOTYP.LE.KODHI(2)) RETURN
C
      WRITE(CMSSG,45)
   45 FORMAT('ILLEGAL OR UNDEFINED FASTBUS MODULE TYPE')
      CALL ERRLOG(LOGUT,LOGUP)
      RETURN
C
   60 IF(MOTYP.GE.KODLO(3).AND.MOTYP.LE.KODHI(3)) RETURN
      IF(MOTYP.EQ.0.OR.MOTYP.EQ.-1)   RETURN
C
      WRITE(CMSSG,65)
   65 FORMAT('ILLEGAL OR UNDEFINED CAMAC MODULE TYPE')
      CALL ERRLOG(LOGUT,LOGUP)
      RETURN
C
   80 IF(MOTYP.GE.KODLO(4).AND.MOTYP.LE.KODHI(4)) RETURN
C
      WRITE(CMSSG,85)
   85 FORMAT('ILLEGAL OR UNDEFINED VME MODULE TYPE')
      CALL ERRLOG(LOGUT,LOGUP)
      RETURN
C
      END
