pacorlib:\
pacorlib.a(boolod.o)\
pacorlib.a(caller.o)\
pacorlib.a(canitqit.o)\
pacorlib.a(caseup1.o)\
pacorlib.a(ckcam.o)\
pacorlib.a(ckclocid.o)\
pacorlib.a(ckcnas.o)\
pacorlib.a(ckfas.o)\
pacorlib.a(ckfer.o)\
pacorlib.a(ckfrite.o)\
pacorlib.a(ckmoty.o)\
pacorlib.a(cknxti.o)\
pacorlib.a(ckunique.o)\
pacorlib.a(ckvmeid.o)\
pacorlib.a(clocass.o)\
pacorlib.a(clradd.o)\
pacorlib.a(cntadd.o)\
pacorlib.a(cntdown.o)\
pacorlib.a(condico.o)\
pacorlib.a(condx.o)\
pacorlib.a(connec.o)\
pacorlib.a(contab.o)\
pacorlib.a(delayx.o)\
pacorlib.a(equate.o)\
pacorlib.a(errlog.o)\
pacorlib.a(errmsg.o)\
pacorlib.a(errorid.o)\
pacorlib.a(fielder.o)\
pacorlib.a(gatecmp.o)\
pacorlib.a(gater.o)\
pacorlib.a(gatmsk.o)\
pacorlib.a(gread.o)\
pacorlib.a(hardass.o)\
pacorlib.a(hardeco.o)\
pacorlib.a(hexval.o)\
pacorlib.a(ifind.o)\
pacorlib.a(isequl.o)\
pacorlib.a(isubb.o)\
pacorlib.a(isval.o)\
pacorlib.a(ityper.o)\
pacorlib.a(joco.o)\
pacorlib.a(kasup4.o)\
pacorlib.a(killer.o)\
pacorlib.a(kinda.o)\
pacorlib.a(kvalu.o)\
pacorlib.a(kvalue.o)\
pacorlib.a(lablman.o)\
pacorlib.a(labloop.o)\
pacorlib.a(lablv.o)\
pacorlib.a(lasnon.o)\
pacorlib.a(laswd.o)\
pacorlib.a(latwdx.o)\
pacorlib.a(leglass.o)\
pacorlib.a(leglnam.o)\
pacorlib.a(lissor.o)\
pacorlib.a(loopex.o)\
pacorlib.a(lsnb.o)\
pacorlib.a(lwdmod3.o)\
pacorlib.a(messlog.o)\
pacorlib.a(modcod.o)\
pacorlib.a(modsav.o)\
pacorlib.a(moduly.o)\
pacorlib.a(motable.o)\
pacorlib.a(namloc.o)\
pacorlib.a(newmsk.o)\
pacorlib.a(nxbl.o)\
pacorlib.a(nxdg.o)\
pacorlib.a(nxnb.o)\
pacorlib.a(pacnit.o)\
pacorlib.a(pass1.o)\
pacorlib.a(pass2.o)\
pacorlib.a(patmsk.o)\
pacorlib.a(patter.o)\
pacorlib.a(pobgen.o)\
pacorlib.a(poblod.o)\
pacorlib.a(riffer.o)\
pacorlib.a(stripath.o)\
pacorlib.a(symsav.o)\
pacorlib.a(tablog.o)\
pacorlib.a(vmeass.o)\
pacorlib.a(vmesav.o)\
pacorlib.a(xiaass.o)\
pacorlib.a(xiachek.o)\
pacorlib.a(xiandx.o)
#
	ranlib pacorlib.a
	@echo pacorlib.a is up-to-date
#
FFLAGS= -g -O0 -fno-automatic
#
.f.o:
	f77 $(FFLAGS) -c  $<
#
	ar rv pacorlib.a $*.o
