#
DOCS= \
aiolib.doc \
asap.doc \
banco.doc \
bando.doc \
charge.doc \
chil.doc \
damm.doc \
fex.doc \
fitu.doc \
funkyfit.doc \
hisadd.doc \
kineq.doc \
lemor.doc \
nuci.doc \
orphlib.doc \
pacor.doc \
poblis.doc \
porting.doc \
rcon.doc \
readme.doc \
scanor.doc \
shapadd.doc \
stope.doc \
stopi.doc \
stopx.doc \
swapo.doc \
trant.doc \
twig.doc \
txx.doc

all: $(DOCS)

install: $(DOCS) hhirf.pro
	install -d $(INSTALLDIR)/doc
	install -p $? $(INSTALLDIR)/doc
