#!/bin/csh -f
echo " "
echo "Using  /tera/mcsq/Dlinux/Dvme/loaddssd"
echo " "
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/kill_acq
set err = $status
if ($err != 0) then
  echo "${0}: Cannot Kill Acquisition System - Error Status = $err"
  exit
endif
echo "Delete the acquisition tasks in the VME processor"
/tera/mcsq/Dlinux/Dvme/kt data_proc >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt testvme >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt VMEtest >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt VMEacq >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt DSSDacq >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt vmemon >& /dev/null
echo " "
echo "Now load the acquisition tasks.  Any error messages here are BAD news."
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/data_proc
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'data_proc' - Error Status = $err"
  exit
endif
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/DSSDacq 1536
set err = $status
if ($err != 0) then
  echo "${0}: Unable to load task 'DSSDacq' - Error Status = $err"
  exit
endif
