#!/bin/csh -f
echo " "
echo "Using  /tera/mcsq/Dlinux/Dvme/loadln"
echo " "
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/stopln
/tera/mcsq/Dlinux/Dvme/kt lnfxx >& /dev/null
/tera/mcsq/Dlinux/Dvme/kt ln_alarm >& /dev/null
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/lnfxx
/tera/mcsq/Dlinux/Dvme/run /tera/mcsq/Dlinux/Dvme/ln_alarm
