C$PROG CALBAK
      SUBROUTINE CALBAK(ILOO,NB)
C
      COMMON/MAINV8/ A(50,50),B(50,50),DET,IFS
      REAL*8         A,       B,       DET
C
      COMMON/AAX/ SPECT(256,19),ISPK(16384),IBAK(16384),ICAL(16384)
      COMMON/BBB/ XAG(250,7),NPK
      COMMON/CCC/ BGD(256),WT(256),YCAL(256),GAU(200),NG(16)
      COMMON/DDD/ IHOL(16),XP(16),AREA(16),BETA(18),LOCA(250),BIAS
      COMMON/EEE/ ID,ILO,IHI,KWD,FWHMA,FWHMB,EOOO,GAINN,WDNC,DELCH,BSTD
      COMMON/FFF/ HWID(16),QFN,QFLO,IFBGD,NTRY,MSN,NCH,KPK,I1,I2
      COMMON/GGG/ MXNPK,MXRGL,MXPIS,NBNF
      COMMON/HHH/ IGAUS,KNBAK,KNVAR,KVW
C
      DIMENSION FRIGB(13)
      DATA  (FRIGB(I),I=1,13)/0.0,.80,1.1,1.28,1.40,1.53,1.57,1.65,
     11.70,1.75,1.80,1.84,1.89/
C
      DATA IF/0/
C
      SAVE
C
C
C     KNBAK=0 SAYS JUST GO OFF AND ZERO THE BACKGROUND
C
      IF(KNBAK.GT.0) GO TO 10
      IA=1
      IF(ILOO.EQ.0) ILOO=3*KWD
      ILO=ILOO+1
      NA=ILO
      GO TO 205
C
C     TRY TO GET AWAY FROM THE DISCONTINUOUS REGION
C
   10 IF(ILOO.GT.0) GO TO 18
      KDO=NCH/10
      IF(KDO.LT.2) KDO=2
      XDO=KDO
      SUM=0.0
      DO 12 I=2,KDO
      SUM=SUM+ISPK(I)
   12 CONTINUE
      IHAV=SUM/(4.0*XDO)
      DO 14 I=2,KDO
      IF(ISPK(I).LT.IHAV) GO TO 14
      IUP=I+3*KWD
      DO 13 J=I,IUP
      IF(ISPK(J).LT.IHAV) GO TO 14
   13 CONTINUE
      GO TO 16
   14 CONTINUE
      GO TO 18
   16 ILOO=IUP
   18 IFIRST=0
      ILO=ILOO+1
      NA=ILO
      KWDD=KWD
      IF(2*(KWDD/2).NE.KWDD) KWDD=KWDD+1
      INC=5*KWDD
      IF(INC.GT.120) INC=120
      INCH=INC/2
      NAA=NA-INCH
      IF(NAA.LT.1) NAA=1
      DO 200 NN=NAA,NB,INC
      IA=NN
      IB=IA+2*INC-1
      IF(IB.GT.(NB+INCH)) IB=NB+INCH
      IF(IB.GT.NCH) IB=NCH
      N=0
      GO TO (20,40),KNBAK
C
C     KNBAK=1 SAYS DO THE FULL BLOWN FITTING
C
   20 NTIMES=3
      DO 30 I=IA,IB
      N=N+1
      SPECT(N,1)=ISPK(I)
      DENO=ABS(SPECT(N,1))
      IF(DENO.LT.1.0) DENO=1.0
      WT(N)=1.0/DENO
   30 CONTINUE
      GO TO 60
C
C     KNBAK=2 SAYS USE ONLY THE SMALLEST POINT FROM EACH GROUP
C     OF SIZE NTOT/10
C
   40 NTOT=IB-IA+1
      NTIMES=1
      NPG=NTOT/10
      IF(10*NPG.LT.NTOT) NPG=NPG+1
      NFRIG=NPG
      IF(NFRIG.GT.13) NFRIG=13
      STADD=FRIGB(NFRIG)
   45 MINI=ISPK(IA)
      NMIN=N+1
      DO 50 I=1,NPG
      N=N+1
      IF(N.GT.NTOT) GO TO 55
      WT(N)=0.0
      SPECT(N,1)=ISPK(I)
      IF(ISPK(I).GE.MINI) GO TO 50
      MINI=ISPK(I)
      NMIN=N
   50 CONTINUE
      DENO=ABS(SPECT(NMIN,1))
      IF(DENO.LT.1.0) DENO=1.0
      WT(NMIN)=1.0/DENO
      GO TO 45
   55 DO 56 I=1,NTOT
      IF(WT(I).EQ.0.0) GO TO 56
      SPECT(I,1)=SPECT(I,1)+STADD*SQRT(SPECT(I,1))
   56 CONTINUE
      N=N-1
   60 NCMP=2
      DO 80 ICM=1,NTIMES
      IF(ICM.GE.2.OR.NTIMES.EQ.1) NCMP=3
      CALL BACKER(NCMP,1,N)
   80 CONTINUE
      N=INCH
      IC=IA+INCH
      IF=IB-INCH
C
C     ZERO IBAK UP TO IC-1 (FIRST TIME AROUND ONLY)
C
      IF(IFIRST.NE.0) GO TO 100
      ICM1=IC-1
      DO 90 I=1,ICM1
      IBAK(I)=0
   90 CONTINUE
      IFIRST=1
C
C     SAVE THE CALCULATED BACKGROUND
C
  100 DO 110 I=IC,IF
      N=N+1
      IBAK(I)=BGD(N)+0.5
  110 CONTINUE
  200 CONTINUE
C
C     ZERO THE REST JUST FOR THE HELL OF IT
C
      IA=IF+1
      IF(IA.GT.NCH) GO TO 215
  205 DO 210 I=IA,NCH
      IBAK(I)=0
  210 CONTINUE
C
  215 RETURN
      END
