C$PROG SUMMER
      SUBROUTINE SUMMER
C
      COMMON/MAINV8/ A(50,50),B(50,50),DET,IFS
      REAL*8         A,       B,       DET
C
      COMMON/AAX/ SPECT(256,19),ISPK(16384),IBAK(16384),ICAL(16384)
      COMMON/BBB/ XAG(250,7),NPK
      COMMON/CCC/ BGD(256),WT(256),YCAL(256),GAU(200),NG(16)
      COMMON/DDD/ IHOL(16),XP(16),AREA(16),BETA(18),LOCA(250),BIAS
      COMMON/EEE/ ID,ILO,IHI,KWD,FWHMA,FWHMB,EOOO,GAINN,WDNC,DELCH,BSTD
      COMMON/FFF/ HWID(16),QFN,QFLO,IFBGD,NTRY,MSN,NCH,KPK,I1,I2
      COMMON/GGG/ MXNPK,MXRGL,MXPIS,NBNF
      COMMON/HHH/ IGAUS,KNBAK,KNVAR,KVW
C
      DIMENSION XLOC(250)
C
      SAVE
C
      NT=NCH-3*KWD
      IF(KNBAK.EQ.0) NT=NCH-KWD
      KWN=KWD
      IHIT=IHI
      ILOT=ILO
      IF(IHI.GT.NT) IHI=NT
      NLN=0
      KWDH=KWD/2
C
      CALL PFIND(ISPK,XLOC,ILO,IHI,KWDH,BIAS,MXNPK,NPK)
C
      NDO=NPK+1
      DO 10 I=1,NDO
      LOCA(I)=XLOC(I)+0.5
   10 CONTINUE
C
C
      DO 500 IP=1,NPK
      IF(FWHMB.NE.0.0) KWN=2*(FWHMA+FWHMB*SQRT(FLOAT(LOCA(IP))))
      IF(2*(KWN/2).LT.KWN) KWN=KWN+1
      IF(KWN.LT.2) KWN=2
      KWA=KWN
      IF(IP.EQ.1) GO TO 170
      IDIF=LOCA(IP)-LOCA(IP-1)
      IF(IDIF.LT.(2*KWN)) KWA=IDIF/2
  170 L1=LOCA(IP)-KWA+1
      KWB=KWN
      IF((IP+1).EQ.NPK) GO TO 172
      IDIF=LOCA(IP+1)-LOCA(IP)
      IF(IDIF.LT.2*KWN) KWB=IDIF/2
  172 L2=LOCA(IP)+KWB
      IF(L2.LT.L1) L2=L1
      AG=0.0
      BG=0.0
      DO 200 I=L1,L2
      BG=BG+IBAK(I)
      AG=AG+ISPK(I)
  200 CONTINUE
      DENO=L2-L1+1
      IF(DENO.LT.1.0) DENO=1.0
      IBG=BG/DENO
      AGG=0.0
      PROD=0.0
      DO 300 I=L1,L2
      ZI=I-1
      ZSPK=ISPK(I)-IBG
      AGG=AGG+ZSPK*ZSPK
      PROD=PROD+ZI*ZSPK*ZSPK
  300 CONTINUE
      AGGX=AGG
      IF(AGGX.LT.1.0) AGGX=1.0
      XAG(IP,7)=XLOC(IP)-1.0
C
      AA=AG-BG
      AAX=ABS(AA)
      IF(AAX.LT.1.0) AAX=1.0
      XAG(IP,1)=AA
      XAG(IP,2)=100.0*SQRT(ABS(AG+BG))/AAX
  500 CONTINUE
      RETURN
      END
