/axp/milner/DDlinux/Dasapux/asaplx.make
/axp/milner/DDlinux/Dasapux/asapred.make
/axp/milner/DDlinux/Dasapux/asapredlx.make
/axp/milner/DDlinux/Dasapux/asapux.make
/axp/milner/DDlinux/Dasortux/asortlx.make
/axp/milner/DDlinux/Dasortux/asortux.make
/axp/milner/DDlinux/Dbancoux/bancolx.make
/axp/milner/DDlinux/Dbancoux/bancoux.make
/axp/milner/DDlinux/Dbandoux/bando.make
/axp/milner/DDlinux/Dbandoux/bandolx.make
/axp/milner/DDlinux/Dbandoux/bandoux.make
/axp/milner/DDlinux/Dchargeux/chargelx.make
/axp/milner/DDlinux/Dchargeux/chargeux.make
/axp/milner/DDlinux/Dchilliblx/chilliblx.make
/axp/milner/DDlinux/Dchillibux/chillibux.make
/axp/milner/DDlinux/Dchilux/chillx.make
/axp/milner/DDlinux/Dchilux/chilux.make
/axp/milner/DDlinux/Ddammliblx/dammliblx.make
/axp/milner/DDlinux/Ddammlibux/X.make
/axp/milner/DDlinux/Ddammlibux/dammliblx.make
/axp/milner/DDlinux/Ddammlibux/dammlibux.make
/axp/milner/DDlinux/Ddammux/dammlx.make
/axp/milner/DDlinux/Ddammux/dammux.make
/axp/milner/DDlinux/Dddlibux/ddliblx.make
/axp/milner/DDlinux/Dddlibux/ddlibux.make
/axp/milner/DDlinux/Dddmanux/ddioux.make
/axp/milner/DDlinux/Dddmanux/ddmanux.make
/axp/milner/DDlinux/Dddmanux/ddmoux.make
/axp/milner/DDlinux/Ddemioux/demio.make
/axp/milner/DDlinux/Ddemioux/focomp.make
/axp/milner/DDlinux/Develxux/evelx.make
/axp/milner/DDlinux/Develxux/evelxlx.make
/axp/milner/DDlinux/Develxux/evelxx.make
/axp/milner/DDlinux/Develxux/evelxxlx.make
/axp/milner/DDlinux/Dexabux/exabux.make
/axp/milner/DDlinux/Dfatrumpux/fatrump.make
/axp/milner/DDlinux/Dfexux/fexlx.make
/axp/milner/DDlinux/Dfexux/fexux.make
/axp/milner/DDlinux/Dfitulibux/fitulib.make
/axp/milner/DDlinux/Dfitulibux/fituliblx.make
/axp/milner/DDlinux/Dfitux/fitu.hhirf.make
/axp/milner/DDlinux/Dfitux/fitu.make
/axp/milner/DDlinux/Dfitux/fitulx.make
/axp/milner/DDlinux/Dfoliux/ccli.make
/axp/milner/DDlinux/Dfoliux/foli.make
/axp/milner/DDlinux/Dfunkyfitux/funkyfitux.make
/axp/milner/DDlinux/Dkinequx/kineqlx.make
/axp/milner/DDlinux/Dkinequx/kinequx.make
/axp/milner/DDlinux/Dlemorliblx/lemorliblx.make
/axp/milner/DDlinux/Dlemorlibux/lemorlibux.make
/axp/milner/DDlinux/Dlemorux/lemor_hhirf.make
/axp/milner/DDlinux/Dlemorux/lemorl001.make
/axp/milner/DDlinux/Dlemorux/lemorlx.make
/axp/milner/DDlinux/Dlemorux/lemorux.make
/axp/milner/DDlinux/Dmildateux/dtst.make
/axp/milner/DDlinux/Dmildatexx/dtst.make
/axp/milner/DDlinux/Dmilibaux/milibalx.make
/axp/milner/DDlinux/Dmilibaux/milibaux.make
/axp/milner/DDlinux/Dmilibbux/milibblx.make
/axp/milner/DDlinux/Dmilibbux/milibbux.make
/axp/milner/DDlinux/Dnuciux/nucilx.make
/axp/milner/DDlinux/Dnuciux/nuciux.make
/axp/milner/DDlinux/Dorphliblx/orphliblx.make
/axp/milner/DDlinux/Dorphlibux/orphlibux.make
/axp/milner/DDlinux/Dscanorliblx/scanorliblx.make
/axp/milner/DDlinux/Dscanorlibux/scanorlibux.make
/axp/milner/DDlinux/Dscanorux/scanor.make
/axp/milner/DDlinux/Dscanorux/scanorlx.make
/axp/milner/DDlinux/Dscanorux/scanorux.make
/axp/milner/DDlinux/Dstopelibux/stopelib.make
/axp/milner/DDlinux/Dstopelibux/stopeliblx.make
/axp/milner/DDlinux/Dstopeux/stope.make
/axp/milner/DDlinux/Dstopiux/stopi.make
/axp/milner/DDlinux/Dstoplibux/stoplib.make
/axp/milner/DDlinux/Dstoplibux/stopliblx.make
/axp/milner/DDlinux/Dstopoux/stopo.make
/axp/milner/DDlinux/Dstopxlibux/stopxlib.make
/axp/milner/DDlinux/Dstopxlibux/stopxliblx.make
/axp/milner/DDlinux/Dstopxux/stopx.make
/axp/milner/DDlinux/Dstuux/stu.make
/axp/milner/DDlinux/Dstuux/stulx.make
/axp/milner/DDlinux/Dswapoux/swapolx.make
/axp/milner/DDlinux/Dswapoux/swapoux.make
/axp/milner/DDlinux/Dtrantux/trant.make
/axp/milner/DDlinux/Dtrantux/trantlib.make
/axp/milner/DDlinux/Dtxxux/txx.make
/axp/milner/DDlinux/Dwindxux/windxux.make
/axp/milner/DDlinux/Dxglibux/xgliblx.make
/axp/milner/DDlinux/Dxglibux/xglibux.make
