#!/bin/csh -f
set ACQ_DIR = `dirname $0`
if ($1 != "") then
   $ACQ_DIR/acq_run stopvme >& /dev/null
   set err = $status
   if ($err == 0) then
      echo "****** WARNING:  VME acquisition has been stopped ******"
   endif
   $ACQ_DIR/m_setup $1
   set err = $status
   if ($err != 0) then
     echo "*** m_setup  FAILED ***"
     exit $err
   endif
endif
$ACQ_DIR/acq_run init
