C$PROG BANLOC
      SUBROUTINE BANLOC(IPX,IDA,IDB,NB,ISHI,LENG,LOC,IERR,MSER)
C
C
      INTEGER*2 BNID,BLEN
C
      INTEGER*4 BLOC
C
      COMMON/BBB/ BNID(880),BLEN(880),BLOC(880),MXBAN,NBAN
C
      COMMON/FFF/ LIST(2002),LPAR(2002),IPSP(2002),IPSI(2002),
     &            MXPAR,NPAR,MINIP,MAXIP,LPARF
C
      COMMON/KKK/ MILF(262144),MILMF(32768),MILC,MILCF,NHWPC,NXDAD,Q,
     &            NUBPC,IGATOF,IMAPOF,NGATL,NMAPL,MXGATL,MXMAPL
C
      INTEGER*2 MILH(524288)
C
      INTEGER*4 MESS(10,2),MSER(10)
      CHARACTER*40 MSC(2)
C
      EQUIVALENCE (MSC(1),MESS(1,1))
      EQUIVALENCE (MILH(1),MILF(1))
C
      DATA  MSC/'REQUESTED BAN-ID,S NOT FOUND           ',
     &          'REQUESTED BAN-ID,S NOT ALL SAME LENGTH '/
C
      SAVE
C
C     **************************************************************
C     RETURNS FULL-WD MIL-LOCATION OF 1ST WD OF BAN-LIST
C     DEFINED BY IDA THRU IDB (ID'S NEED NOT BE CONTIGUOUS)
C     **************************************************************
C
      IERR=0
C
      DO 10 I=1,NBAN
      IF(IDA.EQ.BNID(I)) GO TO 20
   10 CONTINUE
      GO TO 210
C
   20 IA=I
      LENG=BLEN(IA)
      LOCH=BLOC(IA)
      LOC=(LOCH+1)/2
C
      DO 30 I=IA,NBAN
      IF(LENG.NE.BLEN(I)) GO TO 220
      IF(IDB.EQ.BNID(I)) GO TO 40
   30 CONTINUE
      GO TO 210
C
   40 NB=I-IA+1
      LENP=LPAR(IPX)
      ISHI=LOGB2(LENP)-LOGB2(LENG)
      RETURN
C
  210 JJ=1
      GO TO 300
  220 JJ=2
C
  300 DO 310 I=1,10
      MSER(I)=MESS(I,JJ)
  310 CONTINUE
      IERR=JJ
      RETURN
      END
