C$PROG IOERR
      SUBROUTINE IOERR(IOS)
C
      INTEGER*4 MSER(20)
C
      IF(IOS.EQ.0) RETURN
C
      CALL IOSMES(IOS,MSER)
C
      WRITE(0,10)MSER
   10 FORMAT(1H ,'I/O ERROR - ',20A4)
      RETURN
      END
