C$PROG OPERR
      SUBROUTINE OPERR(IOS)
C
      INTEGER*4 MSER(20)
C
      SAVE
C
      IF(IOS.EQ.0) RETURN
C
      CALL IOSMES(IOS,MSER)
C
      WRITE(0,10)MSER
      WRITE(6,10)MSER
   10 FORMAT(1H ,'OPEN ERROR - ',20A4)
      RETURN
      END
