C$PROG QQ
      SUBROUTINE QQ(IAD,LDX)
C
      LOGICAL Q
C
      COMMON/JJJ/ LIN,LOU,LU6,LER,NEREC,NSOL,LHLN,NERR
C
      COMMON/KKK/ MILF(262144),MILMF(32768),MILC,MILCF,NHWPC,NXDAD,Q,
     &            NUBPC,IGATOF,IMAPOF,NGATL,NMAPL,MXGATL,MXMAPL
C
      INTEGER*2 MILM(65536)
C
      EQUIVALENCE (MILM(1),MILMF(1))
C
      SAVE
C
      IF(LDX.LT.0) GO TO 20             !TST FOR FULL-WD MODE
C
      NDX=MILC+IAD
      GO TO 30
C
   20 NDX=2*(MILCF+IAD)-1
C
   30 IF(NDX.GE.32768) GO TO 50
      MILM(NDX)=LDX
      RETURN
C
   50 WRITE(LU6,60)
   60 FORMAT(1H ,'! ! ! MIL-ARRAY OVERFLOW ! ! !')
      STOP
      END
